# Generated by Django 2.2.13 on 2021-03-30 02:45

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bef_content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='编辑正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=mdeditor.fields.MDTextField(verbose_name='摘要'),
        ),
    ]
